# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlugRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, verbose_name='uuid')),
                ('plug', models.FileField(default=b'', upload_to=b'plugs/default', verbose_name='\u6587\u4ef6\u8def\u5f84')),
            ],
            options={
                'verbose_name': '\u63d2\u4ef6\u8bb0\u5f55\u8868',
                'verbose_name_plural': '\u63d2\u4ef6\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='PocTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='\u4efb\u52a1\u521b\u5efa\u65f6\u95f4')),
                ('task_id', models.CharField(max_length=64, verbose_name='\u4efb\u52a1id')),
                ('local_task_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='\u672c\u5730\u4efb\u52a1id')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='\u4efb\u52a1\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='\u4efb\u52a1\u7ed3\u675f\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(b'', '------'), (0, '\u8fd0\u884c\u4e2d'), (1, '\u5df2\u6682\u505c'), (2, '\u5df2\u7ed3\u675f')], verbose_name='\u4efb\u52a1\u72b6\u6001')),
                ('result', models.TextField(blank=True, verbose_name='\u4efb\u52a1\u7ed3\u679c')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.PlugRecord', verbose_name='\u63d2\u4ef6')),
            ],
            options={
                'verbose_name': '\u4efb\u52a1\u8868',
                'verbose_name_plural': '\u4efb\u52a1\u8868',
            },
        ),
    ]
